### ISSUE TITLE
ST-7: Create a DB Starter File

### ISSUE THREAD

**Issue by maxion1234** [Michaelrt86/ITSC-4155-Final-Project#34]
Create a DB Starter File to fill the database with dummy data for testing.

Given-when-then:
Given a mass of student, survey, and survey response data when it needs to be stored or retrieved in an organized matter, then there will be an organized MySQL database matching our ER diagram that is easy to query. 

![Image](https://github.com/user-attachments/assets/f3493d72-7201-4dff-ba7a-95f906ef3347)
![Image](https://github.com/user-attachments/assets/940586b3-8145-4fa6-8a6e-f294b6f19ada)

**Comment by MaryJohnson-Projects** [comment]
Instead of a DB starter file this has been implemented within app.py

**Comment by MaryJohnson-Projects** [comment]
Dummy data is created in the site itself.
