### ISSUE TITLE
ST-8: Implement matching algorithm 

### ISSUE THREAD

**Issue by maxion1234** [Michaelrt86/ITSC-4155-Final-Project#36]
After the algorithm is sketched out, code and implement it into app.py.

Given-when-then:
Given the response data ~6000 students, when a database admin starts the matching process then a matching algorithm should be able to return matches for as many students as possible with corresponding fitness scores that are larger than the fitness scores of random placement.

![Image](https://github.com/user-attachments/assets/cfa9731c-12f1-4ddd-b948-75bd8648c4c9)

**Comment by maxion1234** [comment]
[See scenario on other task](https://github.com/Michaelrt86/ITSC-4155-Final-Project/issues/35#issuecomment-2423156867)

**Comment by Michaelrt86** [comment]
<img width="1280" alt="Matching algorithm" src="https://github.com/user-attachments/assets/f8d5d442-430c-47b4-b602-3422464b31e1">

**Comment by Michaelrt86** [comment]
This is a mockup of the matching algorithm I had made in Python.
