### ISSUE TITLE
ST-10 Create Progress bar element (Subject to design discretion)

### ISSUE THREAD

**Issue by MaryJohnson-Projects** [Michaelrt86/ITSC-4155-Final-Project#46]
As a UNCC student I want there to be feedback during the survey completion.
Add a bar at the bottom of the screen that indicates percent completion of the survey. This will require both CSS and JS to be used. It is possible that this specific story is cut for time as it is considered low priority in the project.

Est Time: 2-3hr

Given-when-then:
Given a student is completing the survey, when they answer a question, a bar at the bottom of the screen will increase in size showing progress. 

![Image](https://github.com/user-attachments/assets/16deeb08-0e7d-4bbc-8d8e-13451adfbca3)

**Comment by maxion1234** [comment]
Progress bar element is not long current with new survey page design.
